// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: auth/create_auth.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AuthCreateService_CreateAuth_FullMethodName = "/AuthCreateService/CreateAuth"
)

// AuthCreateServiceClient is the client API for AuthCreateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthCreateServiceClient interface {
	CreateAuth(ctx context.Context, in *CreateAuthRequest, opts ...grpc.CallOption) (*CreateAuthResponse, error)
}

type authCreateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthCreateServiceClient(cc grpc.ClientConnInterface) AuthCreateServiceClient {
	return &authCreateServiceClient{cc}
}

func (c *authCreateServiceClient) CreateAuth(ctx context.Context, in *CreateAuthRequest, opts ...grpc.CallOption) (*CreateAuthResponse, error) {
	out := new(CreateAuthResponse)
	err := c.cc.Invoke(ctx, AuthCreateService_CreateAuth_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthCreateServiceServer is the server API for AuthCreateService service.
// All implementations should embed UnimplementedAuthCreateServiceServer
// for forward compatibility
type AuthCreateServiceServer interface {
	CreateAuth(context.Context, *CreateAuthRequest) (*CreateAuthResponse, error)
}

// UnimplementedAuthCreateServiceServer should be embedded to have forward compatible implementations.
type UnimplementedAuthCreateServiceServer struct {
}

func (UnimplementedAuthCreateServiceServer) CreateAuth(context.Context, *CreateAuthRequest) (*CreateAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAuth not implemented")
}

// UnsafeAuthCreateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthCreateServiceServer will
// result in compilation errors.
type UnsafeAuthCreateServiceServer interface {
	mustEmbedUnimplementedAuthCreateServiceServer()
}

func RegisterAuthCreateServiceServer(s grpc.ServiceRegistrar, srv AuthCreateServiceServer) {
	s.RegisterService(&AuthCreateService_ServiceDesc, srv)
}

func _AuthCreateService_CreateAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthCreateServiceServer).CreateAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthCreateService_CreateAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthCreateServiceServer).CreateAuth(ctx, req.(*CreateAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthCreateService_ServiceDesc is the grpc.ServiceDesc for AuthCreateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthCreateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AuthCreateService",
	HandlerType: (*AuthCreateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAuth",
			Handler:    _AuthCreateService_CreateAuth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/create_auth.proto",
}
