// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	entity "grpcrest/services/auth/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// AuthUseCase is an autogenerated mock type for the AuthUseCase type
type AuthUseCase struct {
	mock.Mock
}

// CreateAuth provides a mock function with given fields: auth
func (_m *AuthUseCase) CreateAuth(auth *entity.Auth) error {
	ret := _m.Called(auth)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Auth) error); ok {
		r0 = rf(auth)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAuth provides a mock function with given fields: auth
func (_m *AuthUseCase) DeleteAuth(auth *entity.Auth) error {
	ret := _m.Called(auth)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Auth) error); ok {
		r0 = rf(auth)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindUserIdPasswordByEmail provides a mock function with given fields: auth
func (_m *AuthUseCase) FindUserIdPasswordByEmail(auth *entity.Auth) (string, string, error) {
	ret := _m.Called(auth)

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(*entity.Auth) (string, string, error)); ok {
		return rf(auth)
	}
	if rf, ok := ret.Get(0).(func(*entity.Auth) string); ok {
		r0 = rf(auth)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*entity.Auth) string); ok {
		r1 = rf(auth)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(*entity.Auth) error); ok {
		r2 = rf(auth)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateAuth provides a mock function with given fields: auth
func (_m *AuthUseCase) UpdateAuth(auth *entity.Auth) error {
	ret := _m.Called(auth)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Auth) error); ok {
		r0 = rf(auth)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewAuthUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthUseCase creates a new instance of AuthUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthUseCase(t mockConstructorTestingTNewAuthUseCase) *AuthUseCase {
	mock := &AuthUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
