// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Bcrypt_ is an autogenerated mock type for the Bcrypt_ type
type Bcrypt_ struct {
	mock.Mock
}

// CompareHashAndPassword provides a mock function with given fields: _a0, _a1
func (_m *Bcrypt_) CompareHashAndPassword(_a0 []byte, _a1 []byte) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, []byte) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenerateFromPassword provides a mock function with given fields: _a0, _a1
func (_m *Bcrypt_) GenerateFromPassword(_a0 []byte, _a1 int) ([]byte, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, int) ([]byte, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func([]byte, int) []byte); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, int) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewBcrypt_ interface {
	mock.TestingT
	Cleanup(func())
}

// NewBcrypt_ creates a new instance of Bcrypt_. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBcrypt_(t mockConstructorTestingTNewBcrypt_) *Bcrypt_ {
	mock := &Bcrypt_{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
